rbac:
  create: true
defaultBackend:
  enabled: false
controller:
  ingressClass: "nginx"
  config:
    use-proxy-protocol: "true"
  service:
    targetPorts:
      http: http
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    externalTrafficPolicy: "Local"